# Generated by Django 5.1.12 on 2025-10-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("original_url", models.URLField(db_index=True, max_length=2048, unique=True)),
                ("short_code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("clicks_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Short Link",
                "verbose_name_plural": "Short Links",
                "db_table": "links_shortlink",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("clicked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("query_params", models.JSONField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, max_length=2048, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "short_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="links.shortlink",
                    ),
                ),
            ],
            options={
                "verbose_name": "Click",
                "verbose_name_plural": "Clicks",
                "db_table": "links_click",
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(fields=["clicked_at"], name="links_click_clicked_dd3348_idx")
                ],
            },
        ),
    ]
